# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 846f75645a6ca42ff8e21e4720141ef98b9fc32b29f3878cc8105adde56b72a6a8edd54e281eb95b5e8581b066498559a48e38cab2839ae6554612da5111885e

test:
  secret_key_base: a9e06d1236972419df891b0b1b10b94daed2bcfb3806e1a36076b77addbe6f3805f1673fd5a595cc8f0c88b72ac1eb2e9f2c7393be26ac188773c45c186268b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
